/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaApplication1 */

#ifndef _Included_JavaApplication1
#define _Included_JavaApplication1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaApplication1
 * Method:    GenerateROS
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JavaApplication1_GenerateROS
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
