/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ie_nuim_cs_dri_interactROS_ROSInteract */

#ifndef _Included_ie_nuim_cs_dri_interactROS_ROSInteract
#define _Included_ie_nuim_cs_dri_interactROS_ROSInteract
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ie_nuim_cs_dri_interactROS_ROSInteract
 * Method:    GenerateROS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ie_nuim_cs_dri_interactROS_ROSInteract_GenerateROS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ie_nuim_cs_dri_interactROS_ROSInteract
 * Method:    ROSCountNodes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ie_nuim_cs_dri_interactROS_ROSInteract_ROSCountNodes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ie_nuim_cs_dri_interactROS_ROSInteract
 * Method:    GetNeo4jGraphNodes
 * Signature: (J)[Lie/nuim/cs/dri/interactROS/detailednode;
 */
JNIEXPORT jobjectArray JNICALL Java_ie_nuim_cs_dri_interactROS_ROSInteract_GetNeo4jGraphNodes__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ie_nuim_cs_dri_interactROS_ROSInteract
 * Method:    GetNeo4jGraphNodes
 * Signature: (Ljava/lang/String;)[Lie/nuim/cs/dri/interactROS/detailednode;
 */
JNIEXPORT jobjectArray JNICALL Java_ie_nuim_cs_dri_interactROS_ROSInteract_GetNeo4jGraphNodes__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
